// <auto-generated />
using System;
using HappyVeggie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyVeggie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HappyVeggieDbContext))]
    [Migration("20260904070308_LlmUsageLog")]
    partial class LlmUsageLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ActorAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActorAdminId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AdminAuditLogs", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CitationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("AssistantMessages", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AssistantThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("AssistantThreads", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Crop", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IconUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NameUr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("Crops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "tomato",
                            Enabled = true,
                            NameEn = "Tomato",
                            NameUr = "ٹماٹر"
                        },
                        new
                        {
                            Id = "potato",
                            Enabled = true,
                            NameEn = "Potato",
                            NameUr = "آلو"
                        },
                        new
                        {
                            Id = "onion",
                            Enabled = true,
                            NameEn = "Onion",
                            NameUr = "پیااز"
                        },
                        new
                        {
                            Id = "cucumber",
                            Enabled = true,
                            NameEn = "Cucumber",
                            NameUr = "کھیر ی"
                        },
                        new
                        {
                            Id = "capsicum",
                            Enabled = true,
                            NameEn = "Capsicum",
                            NameUr = "شملہ مرچ"
                        },
                        new
                        {
                            Id = "chili",
                            Enabled = true,
                            NameEn = "Chili",
                            NameUr = "مرچ"
                        },
                        new
                        {
                            Id = "eggplant",
                            Enabled = true,
                            NameEn = "Eggplant",
                            NameUr = "بینگن"
                        },
                        new
                        {
                            Id = "okra",
                            Enabled = true,
                            NameEn = "Okra",
                            NameUr = "بھِنڈی"
                        },
                        new
                        {
                            Id = "spinach",
                            Enabled = true,
                            NameEn = "Spinach",
                            NameUr = "پالک"
                        },
                        new
                        {
                            Id = "cabbage",
                            Enabled = true,
                            NameEn = "Cabbage",
                            NameUr = "بند گوبھی"
                        },
                        new
                        {
                            Id = "carrot",
                            Enabled = true,
                            NameEn = "Carrot",
                            NameUr = "گاجر"
                        },
                        new
                        {
                            Id = "lettuce",
                            Enabled = true,
                            NameEn = "Lettuce",
                            NameUr = "لیٹش"
                        });
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.CropCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CropAId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CropBId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropAId");

                    b.HasIndex("CropBId");

                    b.HasIndex("CropAId", "CropBId", "Scope");

                    b.ToTable("CropCompatibility", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CropAId = "tomato",
                            CropBId = "onion",
                            Enabled = true,
                            Reason = "Commonly paired to reduce pests (demo seed).",
                            Relation = 0,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CropAId = "onion",
                            CropBId = "tomato",
                            Enabled = true,
                            Reason = "Commonly paired to reduce pests (demo seed).",
                            Relation = 0,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CropAId = "tomato",
                            CropBId = "potato",
                            Enabled = true,
                            Reason = "Both can share similar pests/diseases (demo seed).",
                            Relation = 1,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CropAId = "potato",
                            CropBId = "tomato",
                            Enabled = true,
                            Reason = "Both can share similar pests/diseases (demo seed).",
                            Relation = 1,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CropAId = "cucumber",
                            CropBId = "capsicum",
                            Enabled = true,
                            Reason = "Compatible spacing/companion growth pattern (demo seed).",
                            Relation = 0,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            CropAId = "capsicum",
                            CropBId = "cucumber",
                            Enabled = true,
                            Reason = "Compatible spacing/companion growth pattern (demo seed).",
                            Relation = 0,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            CropAId = "spinach",
                            CropBId = "onion",
                            Enabled = true,
                            Reason = "Neutral compatibility for on-farm adjacency (demo seed).",
                            Relation = 2,
                            Scope = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            CropAId = "onion",
                            CropBId = "spinach",
                            Enabled = true,
                            Reason = "Neutral compatibility for on-farm adjacency (demo seed).",
                            Relation = 2,
                            Scope = 0
                        });
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualYield")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ActualYieldUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CropZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PredictedYield")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PredictedYieldUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CropZoneId");

                    b.HasIndex("CropZoneId", "Season")
                        .IsUnique();

                    b.ToTable("CropCycles", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.CropZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaCanonicalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AreaInputUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("AreaInputValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CropFreetext")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CropId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ExpectedYieldProvenance")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedYieldUnit")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("ExpectedYieldValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExperimental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("PlantingDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductionAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeedVarietyId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("ProductionAreaId");

                    b.HasIndex("FarmId", "ProductionAreaId");

                    b.ToTable("CropZones", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaAcres")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AreaInputUnit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal>("AreaInputValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BudgetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BudgetCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsNewFarmSetup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Lat")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool>("LetAiChooseCrop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Lng")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PreferredCropFreeText")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PreferredCropId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RegionLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool?>("WaterAccess")
                        .HasColumnType("bit");

                    b.Property<string>("WaterSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farms", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.FarmPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextUsedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("none");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("IsFlagged");

                    b.HasIndex("FarmId", "Version")
                        .IsUnique();

                    b.ToTable("FarmPlans", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Farmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("en");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Farmers", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000001"),
                            Description = "Use mock OTP provider instead of live SMS",
                            Enabled = true,
                            Key = "otp.use_mock",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000002"),
                            Description = "Enable live weather enrichment for digital twin",
                            Enabled = false,
                            Key = "weather.enrichment",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000003"),
                            Description = "Enable live soil enrichment for digital twin",
                            Enabled = false,
                            Key = "soil.enrichment",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000004"),
                            Description = "Use live LLM provider instead of stub",
                            Enabled = false,
                            Key = "llm.live",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.FieldNeighbourEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdjacencyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("CropZoneAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CropZoneBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CropZoneAId");

                    b.HasIndex("CropZoneBId");

                    b.HasIndex("FarmId");

                    b.HasIndex("FarmId", "CropZoneAId", "CropZoneBId");

                    b.ToTable("FieldNeighbourEdges", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.GovernmentCropRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RatePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CropId", "Period");

                    b.ToTable("GovernmentCropRates", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.LlmUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestType");

                    b.ToTable("LlmUsageLogs", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.ProductionArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaCanonicalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AreaInputUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("AreaInputValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GrowingMedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrowingMediumProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("HumidityPercent")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int?>("HumidityProvenance")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StructureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StructureTypeProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int?>("TemperatureProvenance")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ventilation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VentilationProvenance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("TypeCode");

                    b.HasIndex("FarmId", "TypeCode");

                    b.ToTable("ProductionAreas", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.ProductionAreaType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NameUr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Code");

                    b.HasIndex("Category");

                    b.HasIndex("Enabled");

                    b.ToTable("ProductionAreaTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "open_field",
                            Category = 0,
                            Enabled = true,
                            NameEn = "Open Field",
                            NameUr = "کھلا میدان"
                        },
                        new
                        {
                            Code = "shed",
                            Category = 1,
                            Enabled = true,
                            NameEn = "Shed",
                            NameUr = "شیڈ"
                        },
                        new
                        {
                            Code = "greenhouse",
                            Category = 1,
                            Enabled = true,
                            NameEn = "Greenhouse",
                            NameUr = "گرین ہاؤس"
                        },
                        new
                        {
                            Code = "tunnel_polyhouse",
                            Category = 1,
                            Enabled = true,
                            NameEn = "Tunnel / Polyhouse",
                            NameUr = "ٹنل / پولی ہاؤس"
                        },
                        new
                        {
                            Code = "experimental",
                            Category = 2,
                            Enabled = true,
                            NameEn = "Experimental",
                            NameUr = "تجربی"
                        },
                        new
                        {
                            Code = "other_protected",
                            Category = 1,
                            Enabled = true,
                            NameEn = "Other Protected",
                            NameUr = "دیگر محفوظ ماحول"
                        });
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.SeedVariety", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DiseaseResistanceNotes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaturityDays")
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NameUr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("RiskBand")
                        .HasColumnType("int");

                    b.Property<string>("SoilNotes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("VarietyType")
                        .HasColumnType("int");

                    b.Property<string>("WaterNotes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("Enabled");

                    b.ToTable("SeedVarieties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "tomato_hybrid_1",
                            CropId = "tomato",
                            DiseaseResistanceNotes = "Basic fungal resistance (demo)",
                            Enabled = true,
                            MaturityDays = 75,
                            NameEn = "Tomato Hybrid A",
                            NameUr = "ہائبرڈ ٹماٹر اے",
                            RiskBand = 1,
                            SoilNotes = "General vegetable-friendly soil",
                            VarietyType = 0,
                            WaterNotes = "Moderate irrigation; avoid waterlogging"
                        },
                        new
                        {
                            Id = "tomato_openpoll_1",
                            CropId = "tomato",
                            DiseaseResistanceNotes = "Moderate disease tolerance (demo)",
                            Enabled = true,
                            MaturityDays = 90,
                            NameEn = "Tomato Open Pollinated B",
                            NameUr = "اوپن پولینیٹڈ ٹماٹر بی",
                            RiskBand = 1,
                            SoilNotes = "Works across common farm soils",
                            VarietyType = 1,
                            WaterNotes = "Steady watering schedule"
                        },
                        new
                        {
                            Id = "potato_local_1",
                            CropId = "potato",
                            Enabled = true,
                            MaturityDays = 100,
                            NameEn = "Local Potato Variety X",
                            NameUr = "مقامی آلو قسم ایکس",
                            RiskBand = 1,
                            VarietyType = 2
                        },
                        new
                        {
                            Id = "onion_local_1",
                            CropId = "onion",
                            Enabled = true,
                            MaturityDays = 95,
                            NameEn = "Local Onion Variety A",
                            NameUr = "مقامی پیاز قسم اے",
                            RiskBand = 1,
                            VarietyType = 2
                        },
                        new
                        {
                            Id = "cucumber_hybrid_1",
                            CropId = "cucumber",
                            Enabled = true,
                            MaturityDays = 50,
                            NameEn = "Cucumber Hybrid C",
                            NameUr = "ہائبرڈ کھیر ی سی",
                            RiskBand = 1,
                            VarietyType = 0
                        },
                        new
                        {
                            Id = "capsicum_hybrid_1",
                            CropId = "capsicum",
                            Enabled = true,
                            MaturityDays = 80,
                            NameEn = "Capsicum Hybrid D",
                            NameUr = "ہائبرڈ شملہ مرچ ڈی",
                            RiskBand = 1,
                            VarietyType = 0
                        },
                        new
                        {
                            Id = "chili_hybrid_1",
                            CropId = "chili",
                            Enabled = true,
                            MaturityDays = 70,
                            NameEn = "Chili Hybrid E",
                            NameUr = "ہائبرڈ مرچ ای",
                            RiskBand = 1,
                            VarietyType = 0
                        },
                        new
                        {
                            Id = "eggplant_openpoll_1",
                            CropId = "eggplant",
                            Enabled = true,
                            MaturityDays = 95,
                            NameEn = "Eggplant Open Pollinated F",
                            NameUr = "اوپن پولینیٹڈ بینگن ایف",
                            RiskBand = 1,
                            VarietyType = 1
                        },
                        new
                        {
                            Id = "okra_local_1",
                            CropId = "okra",
                            Enabled = true,
                            MaturityDays = 55,
                            NameEn = "Okra Local Variety G",
                            NameUr = "مقامی بھِنڈی قسم جی",
                            RiskBand = 1,
                            VarietyType = 2
                        },
                        new
                        {
                            Id = "spinach_openpoll_1",
                            CropId = "spinach",
                            Enabled = true,
                            MaturityDays = 40,
                            NameEn = "Spinach Open Pollinated H",
                            NameUr = "اوپن پولینیٹڈ پالک ایچ",
                            RiskBand = 1,
                            VarietyType = 1
                        },
                        new
                        {
                            Id = "cabbage_local_1",
                            CropId = "cabbage",
                            Enabled = true,
                            MaturityDays = 75,
                            NameEn = "Cabbage Local Variety I",
                            NameUr = "مقامی بند گوبھی آئی",
                            RiskBand = 1,
                            VarietyType = 2
                        },
                        new
                        {
                            Id = "carrot_local_1",
                            CropId = "carrot",
                            Enabled = true,
                            MaturityDays = 70,
                            NameEn = "Carrot Local Variety J",
                            NameUr = "مقامی گاجر جے",
                            RiskBand = 1,
                            VarietyType = 2
                        },
                        new
                        {
                            Id = "lettuce_local_1",
                            CropId = "lettuce",
                            Enabled = true,
                            MaturityDays = 45,
                            NameEn = "Lettuce Local Variety K",
                            NameUr = "مقامی لیٹش کے",
                            RiskBand = 1,
                            VarietyType = 2
                        });
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.SoilProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FarmerNotes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("NitrogenProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("NitrogenValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("OrganicMatterProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrganicMatterValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("PhValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int?>("PhValueProvenance")
                        .HasColumnType("int");

                    b.Property<int?>("PhosphorusProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("PhosphorusValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("PotassiumProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("PotassiumValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ProductionAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoilType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("SoilTypeProvenance")
                        .HasColumnType("int");

                    b.Property<string>("Texture")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TextureProvenance")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("ProductionAreaId");

                    b.HasIndex("FarmId", "ProductionAreaId")
                        .IsUnique()
                        .HasFilter("[ProductionAreaId] IS NOT NULL");

                    b.ToTable("SoilProfiles", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.TwinSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RefreshedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SoilProviderStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TwinJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WeatherProviderStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .IsUnique();

                    b.ToTable("TwinSnapshots", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.WaterSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvailabilityProvenance")
                        .HasColumnType("int");

                    b.Property<string>("AvailabilityUnit")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("AvailabilityValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("CapacityEstimateProvenance")
                        .HasColumnType("int");

                    b.Property<string>("CapacityEstimateUnit")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("CapacityEstimateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IrrigationMethod")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("IrrigationMethodProvenance")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReliabilityProvenance")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReliabilityValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("SeasonalAvailability")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("SeasonalAvailabilityProvenance")
                        .HasColumnType("int");

                    b.Property<string>("ServedCropZoneIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("Type");

                    b.ToTable("WaterSources", (string)null);
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.AdminUser", "ActorAdmin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorAdmin");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AssistantMessage", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.AssistantThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AssistantThread", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.CropCycle", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.CropZone", "CropZone")
                        .WithMany()
                        .HasForeignKey("CropZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropZone");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.CropZone", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.ProductionArea", "ProductionArea")
                        .WithMany()
                        .HasForeignKey("ProductionAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("ProductionArea");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Farm", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.FarmPlan", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.FieldNeighbourEdge", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.CropZone", null)
                        .WithMany()
                        .HasForeignKey("CropZoneAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.CropZone", null)
                        .WithMany()
                        .HasForeignKey("CropZoneBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.ProductionArea", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany("ProductionAreas")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.ProductionAreaType", "Type")
                        .WithMany("ProductionAreas")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.SeedVariety", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.SoilProfile", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyVeggie.Domain.Entities.ProductionArea", "ProductionArea")
                        .WithMany()
                        .HasForeignKey("ProductionAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Farm");

                    b.Navigation("ProductionArea");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.TwinSnapshot", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.WaterSource", b =>
                {
                    b.HasOne("HappyVeggie.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.AssistantThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Farm", b =>
                {
                    b.Navigation("ProductionAreas");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.Farmer", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("HappyVeggie.Domain.Entities.ProductionAreaType", b =>
                {
                    b.Navigation("ProductionAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
